security:
  oauth2:
    resource:
      filter-order: 3

security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT Example Realm

security:
  jwt:
    client-id: testjwtclientid
    client-secret: XY7kmzoNzl100
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid

spring:
  datasource:
    url: jdbc:sqlserver://localhost
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
     #ddl-auto: create-drop
    database: SQL_SERVER
    show-sql: true
